console.log(navigator);
console.log(navigator.userAgent);
console.log(navigator.cookieEnabled);
console.log(navigator.credentials);
console.log(navigator.languages);
console.log(navigator.appCodeName);
console.log(navigator.appVersion);
console.log(navigator.platform);
console.log(navigator.userActivation);
